version: "3.9"

services:
  mysql:
    image: ubuntu/mysql
    restart: always
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=123456"
      - "MYSQL_DATABASE=blog"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - "./app:/var/www/app"
    working_dir: "/var/www/app"
    networks:
      - app-network

  front:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    volumes:
      - "./front:/var/www/front"
    working_dir: "/var/www/front"
    command: "npm install && npm start"
    ports:
      - "3000:3000"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - app-network

  nginx:
    image: nginx
    restart: always
    depends_on:
      - app
    volumes:
      - "./docker/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge